### PR TITLE
Add Keyword and Icons for API

### PR DESCRIPTION
**Pull request by travisbutcher**
Adding Keyword searches for the API requests.

### CODE REVIEW

**Comment by apfister** [comment]
@travisbutcher do you know how i can add you to be a collaborator here?

**Comment by travisbutcher** [comment]
yes, go to the settings of the repo and you should see collaborators
image

**Comment by apfister** [comment]
i don't have a "settings".. probably because we are under the Esri Org.

**Comment by travisbutcher** [comment]
do you mind if I merge these changes in?  I added a section for keywords into the goals, these are used in created the tags for ArcGIS Online

**Comment by apfister** [comment]
sounds good to me.

**Pull request merged**
